swagger: '2.0'
info:
  title: ExtraerIntencionYDatos
  description: MCP extractor de intenci칩n y datos desde lenguaje natural en espa침ol
  version: 1.0.0
host: TU-SERVIDOR-PUBLICO.com
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: Extraer intenci칩n y dato
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: extraerIntencionYDato
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: prompt_input
          in: body
          required: true
          schema:
            type: object
            properties:
              prompt:
                type: string
                description: Texto en lenguaje natural
      responses:
        200:
          description: Resultado de la extracci칩n
          schema:
            type: object
            properties:
              intencion:
                type: string
              tipo_dato:
                type: string
              valor_dato:
                type: string
